### ISSUE TITLE
Media Visibility

### ISSUE THREAD

**Issue by abvas** [vidstack/vidstack#633]
Hey!

I can't get "Media Visibility" to work

- windows 10
- Chrome 99
- 
I am using this construct:

```
     <vds-media-visibility>
       <vds-aspect ratio>
         <vds-video-player>
           <vds-media-ui slot="ui"></vds-media-ui>
         </vds-video-player>
       </vds-aspect ratio>
     </vds-media-visibility>
```

For tests I use: "https://cdn.jsdelivr.net/npm/@vidstack/player/dist-cdn/define/dangerously-all.js"

Here is an example: https://codepen.io/abvas/pen/wvpMaQb

**Please tell me what am I doing wrong?**

Thanks.

**Comment by mihar-22** [comment]
Hey @abvas you're not doing anything wrong, it's a bug. The player connects to the `<vds-media-visibility>` by dispatching an event when it connects to the DOM. It seems for some reason the element's are defined out of order when using the CDn and the event is not being caught by `<vds-media-visibility>`. We need to design a better solution for pairing elements with the current player. I'll prioritize solving this once I get through getting our playground environment up.

**Comment by mihar-22** [comment]
I've fixed the order of imports so this should be resolved in the [next release](https://github.com/vidstack/vidstack/pull/639).

**Comment by abvas** [comment]
Hey!
Unfortunately after updating to version 1.3.0-next
still can't get "<vds-media-visibility>" to work.

By the way, "<vds-media-sync>" doesn't work either. Probably the same problem.

**Comment by mihar-22** [comment]
Thanks @abvas, I found the visibility element was observing the wrong element. Should be resolved in the next release today.

**Comment by mihar-22** [comment]
You can use this markup to test it once I cut the release.

```html
    <vds-media>
      <vds-media-visibility enter-viewport="play" exit-viewport="pause">
        <vds-media-sync single-playback sync-volume>
          <vds-video
            poster="https://media-files.vidstack.io/poster.png"
            loading="lazy"
            controls
          >
            <video
              poster="https://media-files.vidstack.io/poster-seo.png"
              preload="none"
              src="https://media-files.vidstack.io/720p.mp4"
            ></video>
          </vds-hls>
        </vds-media-sync>
      </vds-media-visibility>
    </vds-media>
```

```css
vds-media,
vds-video {
  width: 100%;
}
```

**Comment by mihar-22** [comment]
This should now be resolved @abvas, let me know how you go 🤞

**Comment by abvas** [comment]
Hey!

After updating v.1.4.0 everything works fine.

Used this markup:

```
    <vds-media>
      <vds-media-visibility enter-viewport="play" exit-viewport="pause">
        <vds-media-sync single-playback sync-volume>
          <vds-aspect-ratio ratio="16/9" min-height="150px" max-height="100vh" >
            <vds-video poster="https://media-files.vidstack.io/poster.png" autoplay controls>
              <video src="https://media-files.vidstack.io/720p.mp4" poster="https://media-files.vidstack.io/poster-seo.png" preload="metadata">
              </video>
            </vds-video>
          </vds-aspect-ratio>
        </vds-media-sync>
      </vds-media-visibility>
    </vds-media>
  </div>
```
  
 Both media-visibility and media-sync and aspect-ratio work great.
 
 Starts working after the first interaction of the user with the page. But, as I understand it, we cannot change this.
 
 Here is an example if someone needs it: [](https://codepen.io/abvas/pen/gOoXEbz)
 
 I look forward to further development and improvement of this project.
 
 Many thanks!
